### ISSUE TITLE
Eliminate use of lazy_static

### ISSUE THREAD

**Issue by josephlr** [cryptocorrosion/cryptocorrosion#22]
We ran into an issue (https://github.com/rust-lang/rust/pull/61393#pullrequestreview-266762413 and https://github.com/rust-random/rand/issues/850) originating with `rand`'s use of these crates.

Essentially,
  - `rand` uses a ChaCha-based implementation for its thread-local RNG `rand-chacha`
  - `rand-chacha` uses `x2-chacha` for the actual ChaCha implementation
  - `x2-chacha` uses `ppv-lite86` for x86 SIMD stuff.
  - `ppv-lite86` uses `lazy_static`

My main concern is with this last dependency. It doesn't seem necessary to [have `dispatch_init` called only once.](https://github.com/josephlr/cryptocorrosion/blob/9a566c972c692d901973f4214ba394a7efd7daad/utils-simd/ppv-lite86/src/x86_64/mod.rs#L234). `is_x86_feature_detected` does the proper caching regardless. Is there a reason your `std` implementation couldn't just work like your [`no_std` implementation](https://github.com/josephlr/cryptocorrosion/blob/9a566c972c692d901973f4214ba394a7efd7daad/utils-simd/ppv-lite86/src/x86_64/mod.rs#L279-L296).

**Comment by gnzlbg** [comment]
The crate appears to only be caching a `fn` type which fits in an `AtomicUsize`, so if for whatever reason the crate wants to continue to do caching, it could replace `lazy_static!` with that.

**Comment by kazcw** [comment]
done in ppv-lite86 0.2.6 / c2-chacha 0.2.3
