### ISSUE TITLE
Use no SIMD variant when no sse2/avx is detected even when the simd feature is set

### ISSUE THREAD

**Issue by bjorn3** [cryptocorrosion/cryptocorrosion#25]
This would be very useful to be able to compile rustc using https://github.com/bjorn3/rustc_codegen_cranelift, as it doesn't support SIMD yet.

**Comment by kazcw** [comment]
I wish I could detect that in general, but I haven't found a way. Compile time detection with target-feature is "yes/maybe"; there's no "no". As for runtime detection, platforms that don't support SIMD intrinsics aren't likely to support is_foo_feature_detected(). So what I had to do for miri is add a special case to the ifdef thicket, a la `#[cfg(not(miri)]]`

Is there a compile-time `#[cfg(...)]` check that could identify no-simd cranelift versions?

**Comment by bjorn3** [comment]
> Is there a compile-time #[cfg(...)] check that could identify no-simd cranelift versions?

No there isnt any cfg. Codegen backends cannot set cfg flags at the moment. What I want is that when both sse2 and avx are not detected using `is_x86_feature_detected!`, it should use the non simd version , like when the simd feature is not enabled, instead of using `unimplemented!()`.

**Comment by kazcw** [comment]
It's unfortunate that something so fundamental cannot yet be identified at compile time. I'll need to measure how much compile time and code size overhead that adds for other x86_64 backends, which wouldn't otherwise need to build in a simd emulation library.

**Comment by kazcw** [comment]
@bjorn3 actually, would a `no_simd` feature work for you?

**Comment by bjorn3** [comment]
That could work.

**Comment by vks** [comment]
> @bjorn3 actually, would a `no_simd` feature work for you?

I think features are supposed to be additive, aren't they?

**Comment by bjorn3** [comment]
> I think features are supposed to be additive, aren't they?

Yes, but disabling simd isnt really removing a feature, just an optimization. Disabling simd is also arguably a "feature", as it allows using c2-chacha without simd support by either the cpu or the codegen backend.

Looking at the code a bit more, it seems that the `_mm_insert_epi64` at https://github.com/cryptocorrosion/cryptocorrosion/blob/e77f1623c012d2bae022d69c21668391019bc3b2/utils-simd/ppv-lite86/src/x86_64/sse2.rs#L344 and other places could be avoided by using [`_mm_loadu_si128`](https://doc.rust-lang.org/stable/core/arch/x86_64/fn._mm_loadu_si128.html) or a similar intrinsic. Those are the main reason that c2-chacha doesnt work with rustc_codegen_cranelift. I havent found a way to support `#[rustc_args_required_const]` yet, as those rely on LLVM inlining and constant propagation before handling SIMD, but cg_clif must do SIMD handling during generation of clif ir and clif doesnt have inlining.

**Comment by vks** [comment]
Is this about compiling `rand` with cranelift? In that case, we could do what is currently done for WASM, which is falling back to using `rand_hc` instead of `rand_chacha`.

**Comment by bjorn3** [comment]
> Is this about compiling rand with cranelift?

Yes

> In that case, we could do what is currently done for WASM, which is falling back to using rand_hc instead of rand_chacha.

At the moment there is no way for a codegen backend to set a cfg feature, so I dont know how to change rand to conditionaly depend on rand_hc when using cg_clif.

**Comment by kazcw** [comment]
`no_simd` is available from ppv-lite86 0.2.8

**Comment by bjorn3** [comment]
Thanks!

**Comment by bjorn3** [comment]
`no_simd` doesn't do anything.

**Comment by mati865** [comment]
I think https://github.com/mati865/cryptocorrosion/commit/dc1dff112919840a98f244b4a617bb7792844e7a would fix `no_simd` feature but I'm not confident if that is proper solution since it would conflict with `simd` feature (mutually exclusive features don't exist: https://github.com/rust-lang/cargo/issues/2980).

After looking at Rust dependency tree I think bumping `rand_chacha` to version 0.2.3 will disable simd: https://github.com/rust-random/rand/commit/4b99567b56f39742f8b6e746dcd910c6d1ed3a93#diff-1518fed4708b2c3e1c4bc69e9dc34775R23 since `ppv-lite86` no longer uses simd by default: https://github.com/cryptocorrosion/cryptocorrosion/commit/785bfbe9b89344de9978cb80758c07e2ca3cbde3

**Comment by bjorn3** [comment]
Maybe ignore the `simd` feature and only use the `no_simd` feature?
