### ISSUE TITLE
LLVM error emitted on targets that don't support SSE2

### ISSUE THREAD

**Issue by tsoutsman** [cryptocorrosion/cryptocorrosion#69]
The target must also not support AVX2, AWX, SSE4.1, and SSE3 for the error to be emitted.

See rust-random/rand#1260 for an example. For some reason, the issue only occurs when building in debug mode.

I'm not knowledgeable enough to fix it but changing [this line](https://github.com/cryptocorrosion/cryptocorrosion/blob/33ec0f37114a8f2f65874dcee31eb579ae640e20/utils-simd/ppv-lite86/src/x86_64/mod.rs#L369) satisfies LLVM.

**Comment by kazcw** [comment]
Thanks for the the report--when I wrote this, all x86-64 targets had SSE2 enabled. It shouldn't be hard to update that assumption; I'll probably do it this weekend if not sooner.

**Comment by kevinaboos** [comment]
Friendly bump on this. thanks!

**Comment by kazcw** [comment]
@kevinaboos I have added `cfg` logic to ppv-lite86 v0.2.17 that should handle this case, but have not had a chance to test it in an x86-64 no-SSE2 environment--I'd appreciate if you could let me know whether this is working correctly for your use case (after a `cargo update` to get v0.2.17).

**Comment by kevinaboos** [comment]
> @kevinaboos I have added `cfg` logic to ppv-lite86 v0.2.17 that should handle this case, but have not had a chance to test it in an x86-64 no-SSE2 environment--I'd appreciate if you could let me know whether this is working as expected for your use case (after a `cargo update` to get v0.2.17).

Absolutely, we'll test it soon and get back to you. Thanks so much!

**Comment by tsoutsman** [comment]
@kazcw it's working, thank you very much.

**Comment by kevinaboos** [comment]
Thanks again!
